// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: time_slots.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTimeSlot = `-- name: CreateTimeSlot :one
INSERT INTO time_slots (id, vendor_id, start_time, end_time, is_booked, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, vendor_id, start_time, end_time, is_booked, created_at, updated_at
`

type CreateTimeSlotParams struct {
	ID        uuid.UUID `json:"id"`
	VendorID  uuid.UUID `json:"vendor_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
	IsBooked  bool      `json:"is_booked"`
}

func (q *Queries) CreateTimeSlot(ctx context.Context, arg CreateTimeSlotParams) (TimeSlot, error) {
	row := q.db.QueryRowContext(ctx, createTimeSlot,
		arg.ID,
		arg.VendorID,
		arg.StartTime,
		arg.EndTime,
		arg.IsBooked,
	)
	var i TimeSlot
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.StartTime,
		&i.EndTime,
		&i.IsBooked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTimeSlot = `-- name: DeleteTimeSlot :one
DELETE FROM time_slots
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteTimeSlot(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteTimeSlot, id)
	err := row.Scan(&id)
	return id, err
}

const getTimeSlot = `-- name: GetTimeSlot :one
SELECT id, vendor_id, start_time, end_time, is_booked, created_at, updated_at
FROM time_slots
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTimeSlot(ctx context.Context, id uuid.UUID) (TimeSlot, error) {
	row := q.db.QueryRowContext(ctx, getTimeSlot, id)
	var i TimeSlot
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.StartTime,
		&i.EndTime,
		&i.IsBooked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTimeSlot = `-- name: UpdateTimeSlot :one
UPDATE time_slots
SET vendor_id = $2,
    start_time = $3,
    end_time = $4,
    is_booked = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, vendor_id, start_time, end_time, is_booked, updated_at
`

type UpdateTimeSlotParams struct {
	ID        uuid.UUID `json:"id"`
	VendorID  uuid.UUID `json:"vendor_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
	IsBooked  bool      `json:"is_booked"`
}

type UpdateTimeSlotRow struct {
	ID        uuid.UUID `json:"id"`
	VendorID  uuid.UUID `json:"vendor_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
	IsBooked  bool      `json:"is_booked"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateTimeSlot(ctx context.Context, arg UpdateTimeSlotParams) (UpdateTimeSlotRow, error) {
	row := q.db.QueryRowContext(ctx, updateTimeSlot,
		arg.ID,
		arg.VendorID,
		arg.StartTime,
		arg.EndTime,
		arg.IsBooked,
	)
	var i UpdateTimeSlotRow
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.StartTime,
		&i.EndTime,
		&i.IsBooked,
		&i.UpdatedAt,
	)
	return i, err
}
